#!/bin/sh

read -r -d '' applescriptCode <<'EOF'
   set dialogText to text returned of (display dialog "Terminating session in 90 minutes" default answer "")
   return dialogText
EOF

dialogText=$(osascript -e "$applescriptCode");

echo $dialogText;

if [ $dialogText == "ok" ]; then
    "{FILE}" & A=$!
    echo $A
    sleep 90*60
    
    osascript -e 'display notification "Closing app in 2 minutes" with title "Timely"'
    sleep 120
    kill -n 1 $A
fi
