#!/bin/sh

read -r -d '' launchApp <<'EOF'
   set dialogText to text returned of (display dialog "Terminating session in {TIME} minutes, type \"ok\" to launch app" default answer "")
   return dialogText
EOF

dialogText=$(osascript -e "$launchApp");

echo $dialogText;

if [ $dialogText == "ok" ]; then
    "{FILE}" & A=$!
    
    sleep "$( expr {TIME} \* 60 )"
    
    osascript -e 'display notification "Closing app in {EXTRA} minutes" with title "Timely"'
    sleep "$( expr {EXTRA} \* 60)"
    kill -n 1 $A
fi
