#!/bin/bash

resources_path="/usr/local/etc/timely"
time=-1
extra_time=-1

testing=0

# maybeee some checkings to make sure the user can't use -t would be nice
while getopts ":t" o; do
    case "${o}" in
        t)
            testing=1
            ;;
    esac
done
if [ $testing -eq 1 ]; then
    shift
    resources_path="$PWD/res"
fi

# $1 - add

function load_config {
    while read -r line
    do
        IFS=' '    
        read -a kv <<< "$line"
        
        k="${kv[0]}"
        v="${kv[1]}"
        case "$k" in
            time)
                time="$v"
                ;;
            extra)
                extra_time="$v"
                ;;
            *)
                echo "unknown setting $k"
                ;;
        esac

    done < "$resources_path/.preferences"
}

usage="usage: timely <add | remove | set | preferences> [executable | minutes]"
usage_add="usage: timely add [executable]"
usage_remove="usage: timely remove [full path to executable]"
usage_list="usage: timely list"

if [ $# -lt 1 ]; then
    echo "$usage"
    exit 1
fi

load_config


if ! [[ "$time" =~ ^[0-9]+$ ]] || ! [[ "$extra_time" =~ ^[0-9]+$ ]] ||  [ "$time" -eq -1 ] || [ "$extra_time" -eq -1 ]; then
    echo "aborting - bad config file"
    exit 1
fi

if [ $1 == "add" ]; then
    if [ $# -eq 2 ] && [ -f "$2" ] && [ -x "$2" ]; then
        path=$(cd "$(dirname "$2")" && pwd)/$(basename "$2")
        # path=`find $PWD -type f | grep "\/$2$"`
        escapedPath=$(echo $path | sed 's_/_\\/_g')

        if grep -q "$path" "$resources_path/.timelies"; then
            echo "Timely already exists"
            exit 1
        fi

        mv "$2" "$2-real"
        touch "$2"
        echo "" > "$2"
 
        cat $resources_path/base_script > "$2"        
        echo `cat "$2" | sed "s/{FILE}/$escapedPath-real/" | sed "s/{TIME}/$time/" | sed "s/{EXTRA}/$extra_time/"` > "$2" 
        
        echo "$path" >> $resources_path/.timelies
        
        chmod +x "$2"
        echo "Created retsrictions for $(basename $2)"
    else
        echo "$usage_add"
    fi

elif [ $1 == "list" ]; then
    echo "You have `wc -l "$resources_path/.timelies" | awk '{print $1}'` timelies"
    cat "$resources_path/.timelies"

elif [ $1 == "remove" ]; then
    if [ $# -eq 2 ]; then
        if grep -q "^$2$" "$resources_path/.timelies"; then
            grep -v "^$2$" "$resources_path/.timelies" > "$resources_path/.temp"; mv "$resources_path/.temp" "$resources_path/.timelies"
            
            rm "$2"
            mv "$2-real" "$2"
            echo "Restrictions removed for $(basename $2)"
        else
            echo "Timely not found"
        fi
    else
        echo "$usage_remove"
    fi
elif [ $1 == "set" ]; then
    if [ $# -eq 3 ]; then
        if grep -q "^$2 " "$resources_path/.preferences"; then
            echo `sed "/^$2 /d" "$resources_path/.preferences"` > "$resources_path/.preferences"
            echo "$2 $3" >> "$resources_path/.preferences"
            echo "$2 updated to $3"
        else
            echo "That's not an existing setting"
        fi
    fi
elif [ $1 == "preferences" ]; then 
    cat "$resources_path/.preferences"
else
    echo "$usage"
fi
